-- google_ratings.sql — GENERATED by scripts/fetch-google-ratings.cjs (2026-06-04),
-- then curated at the §6.3 data-review gate (Rocco, 2026-06-04).
-- Attributed third-party data (display-only). NEVER emitted as the site's own
-- AggregateRating/Review JSON-LD.
--
-- Gate decisions:
--   • Proceed with all valid matches (S.T.O.P 4.4/241 verified; badge is
--     profile-page-only, never in ranked tables, editorial /10 stays the sort).
--   • Quality floor applied: dropped matches with <5 reviews and the lone 1★.
--   • 3 wrong matches dropped (Google returned a different business).
-- Net: 33 companies get a badge; 12 excluded (documented at the bottom);
-- 4 had no Google rating (badge omitted, editorial score still shows).

begin;
-- Silence the per-row deploy-hook during the bulk load; the PR merge/deploy
-- rebuilds the SSG site once with both the component and this data.
alter table public.companies disable trigger trg_company_changed;

-- A1 Cash and Carry → "A1 Cash And Carry" (4.5★ / 1377)
update public.companies set google_place_id = 'ChIJaaCUrGk_K4gRQS7o0sWZbNo', google_rating = 4.5, google_review_count = 1377, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJaaCUrGk_K4gRQS7o0sWZbNo' where slug = 'a1-cash-and-carry';

-- ADL Fournisseur Commercial → "ADL" (4.1★ / 192)
update public.companies set google_place_id = 'ChIJgy47JQ0hyUwR-2hh-rVfKnk', google_rating = 4.1, google_review_count = 192, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJgy47JQ0hyUwR-2hh-rVfKnk' where slug = 'adl-fournisseur-commercial';

-- Apex Electric and Mechanical → "Apex Electric and Mechanical inc." (5★ / 10)
update public.companies set google_place_id = 'ChIJ70MZjjgxK4gR_NDi9hJoSH8', google_rating = 5, google_review_count = 10, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ70MZjjgxK4gR_NDi9hJoSH8' where slug = 'apex-electric-mechanical';

-- Babak Food Equipment → "Babak Food Equipment" (4.9★ / 345)
update public.companies set google_place_id = 'ChIJR15AWNFwhlQRx7ebCzEBRJU', google_rating = 4.9, google_review_count = 345, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJR15AWNFwhlQRx7ebCzEBRJU' where slug = 'babak-food-equipment';

-- BakeMax → "TVI BakeMax" (3.7★ / 7)
update public.companies set google_place_id = 'ChIJMbc-Rgy5oEwRbwdfXJlsy9c', google_rating = 3.7, google_review_count = 7, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJMbc-Rgy5oEwRbwdfXJlsy9c' where slug = 'bakemax';

-- Brama Inc. → "Brama Food Equipment" (4.4★ / 24)
update public.companies set google_place_id = 'ChIJZZDy-HEuK4gRDY5I4A0fvVg', google_rating = 4.4, google_review_count = 24, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJZZDy-HEuK4gRDY5I4A0fvVg' where slug = 'brama';

-- Canada Food Equipment Ltd → "Canada Food Equipment Ltd" (4.3★ / 205)
update public.companies set google_place_id = 'ChIJj4VKS9w3K4gR83CnjEIcvdE', google_rating = 4.3, google_review_count = 205, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJj4VKS9w3K4gR83CnjEIcvdE' where slug = 'canada-food-equipment';

-- Canadian Restaurant Supply → "Canadian Restaurant Supply" (4.5★ / 107)
update public.companies set google_place_id = 'ChIJG2ioDNSMfVMRaDYDbuKzCSU', google_rating = 4.5, google_review_count = 107, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJG2ioDNSMfVMRaDYDbuKzCSU' where slug = 'canadian-restaurant-supply';

-- Celco Inc. → "Celco Inc." (4.2★ / 22)
update public.companies set google_place_id = 'ChIJM8v1j6g_K4gRjZDU5SR2teg', google_rating = 4.2, google_review_count = 22, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJM8v1j6g_K4gRjZDU5SR2teg' where slug = 'celco';

-- Chefco Kitchen & Restaurant Supplies → "Chefco Kitchen & Restaurant Supplies" (4.3★ / 12)
update public.companies set google_place_id = 'ChIJl-E9m9PT1IkRFJ1Y7PftexM', google_rating = 4.3, google_review_count = 12, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJl-E9m9PT1IkRFJ1Y7PftexM' where slug = 'chefco';

-- Continental Restaurant Equipment → "Continental Restaurant Equipment" (4.5★ / 19)
update public.companies set google_place_id = 'ChIJkcP7lI8zK4gRqFPO8xJYaFM', google_rating = 4.5, google_review_count = 19, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJkcP7lI8zK4gRqFPO8xJYaFM' where slug = 'continental-restaurant-equipment';

-- Doyon Despres → "Doyon Després" (4.4★ / 257)
update public.companies set google_place_id = 'ChIJVRw30LiXuEwRSxp9eva0URw', google_rating = 4.4, google_review_count = 257, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJVRw30LiXuEwRSxp9eva0URw' where slug = 'doyon-despres';

-- Econolease Financial Services → "EconoLease" (4.4★ / 114)
update public.companies set google_place_id = 'ChIJLaAmm8jV1IkRebeRUV91muM', google_rating = 4.4, google_review_count = 114, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJLaAmm8jV1IkRebeRUV91muM' where slug = 'econolease';

-- Fincap Financial Group → "Fincap Financial Group" (4.9★ / 119)
update public.companies set google_place_id = 'ChIJC_gAN5AbzkwRQPAF5WqeokM', google_rating = 4.9, google_review_count = 119, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJC_gAN5AbzkwRQPAF5WqeokM' where slug = 'fincap-financial-group';

-- Foundry Kitchens → "Foundry Commercial Kitchens" (4.3★ / 21)
update public.companies set google_place_id = 'ChIJJ5VDJG1xhlQRoaKgSlIyalY', google_rating = 4.3, google_review_count = 21, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJJ5VDJG1xhlQRoaKgSlIyalY' where slug = 'foundry-kitchens';

-- GBS Foodservice Equipment → "GBS Foodservice Equipment" (4.8★ / 73)
update public.companies set google_place_id = 'ChIJN1Tn3wlDK4gR69O0iOvNiC4', google_rating = 4.8, google_review_count = 73, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJN1Tn3wlDK4gR69O0iOvNiC4' where slug = 'gbs-foodservice';

-- Hubert Canada → "Hubert Co LLC" (2.6★ / 11) — address matches Markham; low but real
update public.companies set google_place_id = 'ChIJ32qWyNzU1IkRF6uf2ETBJAg', google_rating = 2.6, google_review_count = 11, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ32qWyNzU1IkRF6uf2ETBJAg' where slug = 'hubert-canada';

-- iFoodEquipment.ca → "iFoodEquipment" (4.2★ / 15)
update public.companies set google_place_id = 'ChIJ1_ivt1aZLIgR2k25mQDt7T4', google_rating = 4.2, google_review_count = 15, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ1_ivt1aZLIgR2k25mQDt7T4' where slug = 'ifoodequipment';

-- Igloo Food Equipment → "Igloo Food Equipment" (4.4★ / 286)
update public.companies set google_place_id = 'ChIJNZ3iZycwK4gRB3Vav0pQ3Bo', google_rating = 4.4, google_review_count = 286, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJNZ3iZycwK4gRB3Vav0pQ3Bo' where slug = 'igloo-food-equipment';

-- J.F.S. Restaurant Equipment → "JFS Restaurant Equipment Ltd" (4.5★ / 30)
update public.companies set google_place_id = 'ChIJPaJ_RSYxK4gRvLMA0tqfAIg', google_rating = 4.5, google_review_count = 30, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJPaJ_RSYxK4gRvLMA0tqfAIg' where slug = 'jfs-restaurant-equipment';

-- KAF Bar Supplies → "KAF Bar and Restaurant Supplies" (4.9★ / 35)
update public.companies set google_place_id = 'ChIJGeYKFZU4K4gRnoCQlaVmAgs', google_rating = 4.9, google_review_count = 35, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJGeYKFZU4K4gRnoCQlaVmAgs' where slug = 'kaf-bar-supplies';

-- MB Food Equipment → "MB Food Equipment" (5★ / 84)
update public.companies set google_place_id = 'ChIJL7pQ96pdK4gRB05bAgGkBAU', google_rating = 5, google_review_count = 84, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJL7pQ96pdK4gRB05bAgGkBAU' where slug = 'mb-food-equipment';

-- MCK Equipment → "MCK Equipment" (4.3★ / 18)
update public.companies set google_place_id = 'ChIJzYGSoFj3BFMRb5aH5w8ZGt8', google_rating = 4.3, google_review_count = 18, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJzYGSoFj3BFMRb5aH5w8ZGt8' where slug = 'mck-equipment';

-- Mehmi Financial Group → "Mehmi Financial Group …" (4.9★ / 70)
update public.companies set google_place_id = 'ChIJ9UzsJTQVK4gR9OVeputnOnY', google_rating = 4.9, google_review_count = 70, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ9UzsJTQVK4gR9OVeputnOnY' where slug = 'mehmi-financial-group';

-- MP HVAC Corporation → "MP HVAC | Restaurant Hood | Commercial HVAC" (4.8★ / 55)
update public.companies set google_place_id = 'ChIJ_ff6w6gtK4gRsYPVH8Lq2tA', google_rating = 4.8, google_review_count = 55, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ_ff6w6gtK4gRsYPVH8Lq2tA' where slug = 'mp-hvac';

-- Nella Cutlery & Food Equipment → "Nella Cutlery Toronto" (3.8★ / 972)
update public.companies set google_place_id = 'ChIJFS7n8CYwK4gRVqmRXV0TEKk', google_rating = 3.8, google_review_count = 972, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJFS7n8CYwK4gRVqmRXV0TEKk' where slug = 'nella-cutlery';

-- Paragon Food Equipment → "Paragon Food Equipment" (4.7★ / 178)
update public.companies set google_place_id = 'ChIJYft9dW1xhlQR-h3n6jyfWmU', google_rating = 4.7, google_review_count = 178, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJYft9dW1xhlQR-h3n6jyfWmU' where slug = 'paragon-food-equipment';

-- Russell Hendrix Foodservice Equipment → "Russell Hendrix Sales Office" (4.5★ / 40)
update public.companies set google_place_id = 'ChIJNew47-Q3K4gRMKM9vxSyumA', google_rating = 4.5, google_review_count = 40, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJNew47-Q3K4gRMKM9vxSyumA' where slug = 'russell-hendrix';

-- Shop at Stop Restaurant Supply → "s.t.o.p. Restaurant Supply" (4.4★ / 241) — VERIFIED
update public.companies set google_place_id = 'ChIJ1_NG25mMK4gRMkPRMFOZhP4', google_rating = 4.4, google_review_count = 241, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ1_NG25mMK4gRMkPRMFOZhP4' where slug = 'shop-at-stop';

-- TFI Food Equipment Solutions → "TFI Food Equipment Solutions" (4.6★ / 9)
update public.companies set google_place_id = 'ChIJp8eRjw45K4gRJGg6mwbKKOM', google_rating = 4.6, google_review_count = 9, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJp8eRjw45K4gRJGg6mwbKKOM' where slug = 'tfi-food-equipment';

-- The Cook's Mate → "Cook's Mate Restaurant Equipment" (4.5★ / 16)
update public.companies set google_place_id = 'ChIJRxFvJh_S1IkR0z62YF6-sy4', google_rating = 4.5, google_review_count = 16, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJRxFvJh_S1IkR0z62YF6-sy4' where slug = 'the-cooks-mate';

-- United Trimen → "United Trimen" (3.2★ / 18)
update public.companies set google_place_id = 'ChIJ5ZmL8ohSV0AR4o9gJGewZis', google_rating = 3.2, google_review_count = 18, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJ5ZmL8ohSV0AR4o9gJGewZis' where slug = 'united-trimen';

-- Zanduco Restaurant Equipment & Supplies → "Zanduco Restaurant Equipment & Supplies" (4.6★ / 319)
update public.companies set google_place_id = 'ChIJFfcin3ZGK4gREqlm6xpLrd0', google_rating = 4.6, google_review_count = 319, google_rating_as_of = '2026-06-04', google_place_url = 'https://search.google.com/local/reviews?placeid=ChIJFfcin3ZGK4gREqlm6xpLrd0' where slug = 'zanduco';

alter table public.companies enable trigger trg_company_changed;
commit;

-- ───────────────────────── EXCLUDED at the §6.3 gate ─────────────────────────
-- Wrong match (Google returned a different business — fix via the admin editor
-- by pasting the correct place_id if/when found):
--   • krg-hospitality            → "Dineen Coffee Co." 4.3/3454 (a café; 0% match)
--   • avondale-commercial-solutions → "Repairus Commercial Refrigeration…" 5/12
--   • fried-sage-hospitality     → "Sage Hospitality" 5/4 (separate brand; friedsage.com is the real one)
--
-- Quality floor (<5 reviews — too thin to be meaningful):
--   • bouthillette-parizeau (BPA) 5/1, enterprise-restaurant-consulting 5/4,
--     franchise-360 5/1, kaizen-foodservice 5/1, kitchen-treasure 3/2,
--     ontario-restaurant-supply 3.7/3, proxpedite 5/1, wd-colledge 5/4
-- Lone 1-star (misleading single review):
--   • browne-foodservice 1/1
--
-- No Google rating found (no badge; editorial /10 still shows):
--   • commercial-kitchen-build, fsstrategy, hesco-foodservice, newcap-leasing
