-- ten_companies_per_service.sql
-- Generated by scripts/build-companies-seed.cjs
-- Adds verified real Canadian (Ontario-preferred) commercial kitchen
-- equipment companies so every /services/[slug] category lists >=10
-- suppliers (Price Match kept truthful at 7). All ranking composites are
-- below Shop at Stop (9.4); S.T.O.P remains the #1 listing.

begin;

-- Silence the per-row deploy-hook during the bulk load; the merge/deploy
-- to main rebuilds the SSG site once from the new data.
alter table public.companies disable trigger trg_company_changed;

-- Truthful correction: remove unsupported Price Match tags.
update public.companies set services = ARRAY['Commercial Equipment Procurement', 'Equipment Consulting']::text[] where slug = 'nella-cutlery';
update public.companies set services = ARRAY['Commercial Equipment Procurement']::text[] where slug = 'chefco';
update public.companies set services = ARRAY['Commercial Equipment Procurement']::text[] where slug = 'igloo-food-equipment';

-- TFI Food Equipment Solutions
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'TFI Food Equipment Solutions', 'tfi-food-equipment', 'TFI Food Equipment Solutions is one of Canada’s largest commercial foodservice equipment suppliers, with over 60 years in business and a Mississauga showroom plus a Bolton parts warehouse. It handles equipment sales, financing and leasing, professional installation, training and 24/7 service for national chains and independent operators.',
  'https://www.tficanada.com', '(905) 790-2211', NULL,
  '{"street":"5945 Airport Rd, Suite 170","city":"Mississauga","province":"Ontario","postal_code":"L4V 1R9"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing', 'Installation Services', 'Account Management', 'Equipment Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":8,"customer_reviews":7.5,"industry_experience":8,"response_time":7.5,"pricing_transparency":7,"certifications":7}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- United Trimen
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'United Trimen', 'united-trimen', 'United Trimen is a North York based commercial foodservice equipment and smallwares distributor and a subsidiary of Gordon Food Service. It designs, sells and installs commercial kitchen solutions for stadiums, hospitals and restaurant chains, offering a single nationwide source backed by a 24-hour service hotline.',
  'https://unitedtrimen.com', '1-800-461-0000', 'sales@unitedtrimen.com',
  '{"street":"1250 Ormont Dr","city":"Toronto","province":"Ontario","postal_code":"M9L 2V4"}'::jsonb,
  ARRAY['Installation Services', 'Account Management', 'Design & Technical Drawings', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":8,"customer_reviews":7.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":7,"certifications":7}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Doyon Despres
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Doyon Despres', 'doyon-despres', 'Doyon Despres is one of Quebec’s largest full-service foodservice equipment dealers, fabricators and suppliers, formed from the merger of Doyon Cuisine and Despres Laporte. It carries thousands of products across a network of branches, provides commercial kitchen design, and publishes a guaranteed best-price policy.',
  'https://www.doyondespres.com', '1-866-444-1110', NULL,
  '{"street":"525 rue du Marais","city":"Quebec City","province":"Quebec","postal_code":"G1M 2Y2"}'::jsonb,
  ARRAY['Price Match', 'Commercial Equipment Procurement', 'Design & Technical Drawings', 'Installation Services', 'Account Management']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":8,"customer_reviews":7.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":7,"certifications":7}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- HESCO Foodservice
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'HESCO Foodservice', 'hesco-foodservice', 'HESCO is a commercial kitchen and restaurant equipment dealer with locations in Edmonton, Calgary and Toronto. It offers kitchen design, equipment sales and consulting, professional installation, and a financing and leasing program delivered through partners Econolease and SilverChef.',
  'https://hesco.ca', '(437) 568-2013', NULL,
  '{"street":null,"city":"Toronto","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Design & Technical Drawings', 'Equipment Consulting', 'Equipment Financing', 'Equipment Leasing', 'Installation Services']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7.5,"customer_reviews":7,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Hubert Canada
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Hubert Canada', 'hubert-canada', 'Hubert Canada is a Markham based distributor of foodservice equipment, supplies and food-merchandising solutions. It serves multi-location and retail foodservice operators with tailored account programs spanning equipment selection, rollout and ongoing optimization, supported by dedicated account-management staff.',
  'https://www.hubert.ca', '1-888-835-7929', NULL,
  '{"street":"20 Valleywood Drive, Suite 108","city":"Markham","province":"Ontario","postal_code":"L3R 6G1"}'::jsonb,
  ARRAY['Account Management', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7.5,"customer_reviews":7,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Econolease Financial Services
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Econolease Financial Services', 'econolease', 'Econolease is a dedicated equipment financing provider for the hospitality and foodservice industry, widely cited as a leading Canadian commercial-kitchen equipment financier. It offers leases, loans and a Rent-Try-Buy program, each supported by a dedicated account manager. It is a Certified B Corporation.',
  'https://www.econolease.com', '1-888-473-9309', NULL,
  '{"street":"30 Rolark Drive","city":"Toronto","province":"Ontario","postal_code":"M1R 4G2"}'::jsonb,
  ARRAY['Equipment Financing', 'Equipment Leasing', 'Account Management']::text[],
  ARRAY['Certified B Corporation']::text[],
  '[]'::jsonb, false, '{"service_range":7.5,"customer_reviews":7,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Bouthillette Parizeau (BPA)
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Bouthillette Parizeau (BPA)', 'bouthillette-parizeau', 'Bouthillette Parizeau (BPA) is a Canadian engineering and consulting firm with a dedicated Food Services division and offices across Canada, including Toronto. It provides study and design of commercial, institutional and agrifood kitchens, including functional programming, layouts, CAD drawings, equipment consulting and budgeting.',
  'https://bpa.ca', '(416) 499-8000', NULL,
  '{"street":"200 King St. West, Suite 310","city":"Toronto","province":"Ontario","postal_code":"M5H 3T4"}'::jsonb,
  ARRAY['Design & Technical Drawings', 'Equipment Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7.5,"customer_reviews":7,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Browne Foodservice
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Browne Foodservice', 'browne-foodservice', 'Browne Foodservice (Browne & Co.) is an Ontario based designer, manufacturer and distributor of foodservice smallwares and equipment including cookware, tabletop, buffet and barware. With roughly 75 years in business, it serves foodservice and retail through a regional account-management and national-accounts structure.',
  'https://brownefoodservice.com', '1-866-475-6104', 'cs@browneco.com',
  '{"street":"390 Addison Hall Circle","city":"Aurora","province":"Ontario","postal_code":"L4G 7C7"}'::jsonb,
  ARRAY['Account Management', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Celco Inc.
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Celco Inc.', 'celco', 'Celco is a Mississauga based, Canada-wide distributor of commercial foodservice equipment founded in 1975. It supports multi-location restaurant brands across foodservice, grocery, healthcare and institutional sectors with a network of market specialists, a consultative approach, plus equipment training, installation and service.',
  'https://www.celco.ca', '(905) 364-5200', NULL,
  '{"street":"6135 Danville Rd","city":"Mississauga","province":"Ontario","postal_code":"L5T 2H7"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Consulting', 'Installation Services', 'Account Management']::text[],
  ARRAY['MAFSI member']::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- BakeMax
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'BakeMax', 'bakemax', 'BakeMax (Titan Ventures International) is a Canadian bakery, pizza and commercial kitchen equipment manufacturer and dealer with a national dealer network. It supplies a broad range of foodservice equipment and offers restaurant equipment financing and leasing through a partnership with Econolease.',
  'https://bakemax.com', '1-800-565-2253', 'OrderDesk@BakeMax.com',
  '{"street":"20 Caribou St","city":"Moncton","province":"New Brunswick","postal_code":"E1H 0P3"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- KAIZEN Foodservice Planning & Design
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'KAIZEN Foodservice Planning & Design', 'kaizen-foodservice', 'KAIZEN Foodservice Planning & Design is an Oakville based, full-service foodservice planning and design consultancy serving the institutional sector. Its FCSI-credentialed consultants, project managers and REVIT technologists deliver facility design, equipment specification and operational advisory services alongside project architects and engineers.',
  'https://www.kaizenfood.com', '(905) 338-3222', NULL,
  '{"street":"Unit 14, 1525 Cornwall Rd","city":"Oakville","province":"Ontario","postal_code":"L6J 0B2"}'::jsonb,
  ARRAY['Design & Technical Drawings', 'Equipment Consulting', 'Restaurant Consulting']::text[],
  ARRAY['FCSI Professional Members']::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Paragon Food Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Paragon Food Equipment', 'paragon-food-equipment', 'Paragon Food Equipment is a Vancouver based commercial restaurant and kitchen equipment dealer that has served foodservice professionals for roughly 40 years and ships across Canada. It carries top-brand equipment and smallwares, runs a documented Price Match Guarantee, and offers lease, rent and financing options.',
  'https://www.paragondirect.ca', '(604) 255-9991', NULL,
  '{"street":"760 E. Hastings St","city":"Vancouver","province":"British Columbia","postal_code":"V6A 1R5"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing', 'Price Match']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7.5,"response_time":7,"pricing_transparency":6.5,"certifications":6.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- GBS Foodservice Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'GBS Foodservice Equipment', 'gbs-foodservice', 'GBS Foodservice Equipment is an Oakville based national distributor and service provider, founded in 1974, representing 18 leading lines of foodservice equipment. It supports customers through a coast-to-coast service network of on-staff technicians and partner service companies and a dedicated account-management team.',
  'https://gbscooks.com', '(905) 829-5534', NULL,
  '{"street":"2871 Brighton Road","city":"Oakville","province":"Ontario","postal_code":"L6H 6C9"}'::jsonb,
  ARRAY['Account Management', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- fsSTRATEGY Inc.
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'fsSTRATEGY Inc.', 'fsstrategy', 'fsSTRATEGY is a professional consulting firm serving the hospitality industry with special emphasis on foodservice, operating from Toronto and Montreal. It delivers strategic and business plans, feasibility analyses, concept development, operations reviews, menu optimization and foodservice master plans.',
  'https://www.fsstrategy.com', '(416) 229-2290', 'nextsteps@fsstrategy.com',
  '{"street":null,"city":"Toronto","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting', 'Design & Technical Drawings', 'Equipment Consulting']::text[],
  ARRAY['CMC-Canada member', 'ISHC member']::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- NewCap Leasing
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'NewCap Leasing', 'newcap-leasing', 'NewCap Leasing is a Canadian commercial equipment leasing and financing firm founded in 2012 that finances new and used restaurant and foodservice equipment including refrigeration, ovens, ice machines and mixers. It offers lease-to-own, working capital loans and equipment refinancing with fast approvals across Canada.',
  'https://www.newcapleasing.com', '(416) 645-0286', NULL,
  '{"street":"222 Norfinch Drive","city":"Toronto","province":"Ontario","postal_code":"M3N 1X8"}'::jsonb,
  ARRAY['Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Babak Food Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Babak Food Equipment', 'babak-food-equipment', 'Babak Food Equipment is a Burnaby based commercial restaurant equipment dealer, with a Laval office, offering equipment sales, service and repair, consultation and design, metal fabrication, and leasing and financing options. It also advertises price matching, subject to some restrictions.',
  'https://babakfoodequipment.com', '(604) 566-9747', NULL,
  '{"street":"7190 Randolph Ave","city":"Burnaby","province":"British Columbia","postal_code":"V5J 4W6"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Consulting', 'Design & Technical Drawings', 'Equipment Financing', 'Equipment Leasing', 'Installation Services', 'Price Match', 'Restaurant Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- ADL Fournisseur Commercial
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'ADL Fournisseur Commercial', 'adl-fournisseur-commercial', 'ADL Fournisseur Commercial is a Laval based commercial restaurant equipment supplier operating since 1988. It imports, manufactures and sells commercial cooking equipment, refrigeration, stainless steel work tables, food-prep machinery and walk-in cold rooms, advertises a best-price policy, offers financing, and delivers and installs cold rooms.',
  'https://goadl.com', '1-800-463-7113', 'info@goadl.com',
  '{"street":"1639 Autoroute 440 Ouest","city":"Laval","province":"Quebec","postal_code":"H7L 3W3"}'::jsonb,
  ARRAY['Price Match', 'Commercial Equipment Procurement', 'Equipment Financing', 'Installation Services']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- J.F.S. Restaurant Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'J.F.S. Restaurant Equipment', 'jfs-restaurant-equipment', 'J.F.S. Restaurant Equipment is a Toronto based restaurant equipment and supply store founded in 1979, serving the GTA. It sources and supplies commercial kitchen equipment, tableware, bar supplies and furniture, offers practical equipment guidance, and provides lease-purchase options.',
  'https://www.jfsltd.com', '(416) 242-2971', NULL,
  '{"street":"2009 Lawrence Ave W, Unit 18","city":"Toronto","province":"Ontario","postal_code":"M9N 3V2"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Consulting', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- KRG Hospitality
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'KRG Hospitality', 'krg-hospitality', 'KRG Hospitality is a hospitality consulting agency founded in 2009 specializing in pre-opening strategy for bars, restaurants and hotels. It delivers feasibility studies, concept and brand development, business plans, financial modeling, menu development and end-to-end project coordination.',
  'https://krghospitality.com', '1-866-575-9552', 'Success@KRGhospitality.com',
  '{"street":"140 Yonge Street","city":"Toronto","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":7,"customer_reviews":6.5,"industry_experience":7,"response_time":6.5,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Brama Inc.
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Brama Inc.', 'brama', 'Brama is a Vaughan based supplier of commercial kitchen and foodservice equipment and supplies operating since 1982. It runs a showroom and an extensive product catalog serving restaurants across Toronto and the GTA.',
  'https://bramainc.com', '(905) 760-9200', 'customer@bramainc.com',
  '{"street":"175 Romina Drive","city":"Vaughan","province":"Ontario","postal_code":"L4K 4V3"}'::jsonb,
  ARRAY['Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Foundry Kitchens
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Foundry Kitchens', 'foundry-kitchens', 'Foundry Kitchens is a Canadian foodservice design agency, custom stainless fabrication shop and equipment dealership established in 2001. It provides foodservice facility design, equipment supply and installation, and actively serves the Greater Toronto Area in addition to its Vancouver base.',
  'https://foundrykitchens.com', '(604) 216-2566', 'info@foundrykitchens.com',
  '{"street":"1020 East Cordova Street","city":"Vancouver","province":"British Columbia","postal_code":"V6A 4A3"}'::jsonb,
  ARRAY['Design & Technical Drawings', 'Commercial Equipment Procurement', 'Installation Services']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- ProXpedite Inc.
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'ProXpedite Inc.', 'proxpedite', 'ProXpedite is a London, Ontario firm founded in 2014 specializing in commercial kitchen design and installation. It sources equipment, stages and consolidates delivery from its warehouses, and installs complete kitchens including exhaust hoods and refrigeration using certified installers across the GTA and Western Ontario.',
  'https://proxpedite.ca', '1-877-776-9123', 'info@proxpedite.com',
  '{"street":"4226 Raney Cres.","city":"London","province":"Ontario","postal_code":"N6L 1C3"}'::jsonb,
  ARRAY['Design & Technical Drawings', 'Installation Services', 'Commercial Equipment Procurement', 'Equipment Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Continental Restaurant Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Continental Restaurant Equipment', 'continental-restaurant-equipment', 'Continental Restaurant Equipment is a Toronto supplier of commercial kitchen equipment, refrigeration and cooking equipment in business since 1994. It offers pre- and post-purchase support from experienced equipment people and equipment financing through an Econolease partnership.',
  'https://continentalrestaurantequipment.ca', '(416) 783-5907', 'continentalrestaurantequipment@gmail.com',
  '{"street":"287 Bridgeland Ave","city":"Toronto","province":"Ontario","postal_code":"M6A 1Z4"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Consulting', 'Equipment Financing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Mehmi Financial Group
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Mehmi Financial Group', 'mehmi-financial-group', 'Mehmi Financial Group is an Ontario based lending and leasing firm that structures restaurant and foodservice equipment financing, including loans, leases, sale-leaseback and equipment lines of credit, for ranges, fryers, dishwashers, walk-ins and ice machines, with fast approvals across Canada.',
  'https://www.mehmigroup.com', '(437) 777-5901', NULL,
  '{"street":"77 City Centre Dr, Suite 501","city":"Mississauga","province":"Ontario","postal_code":"L5B 1M5"}'::jsonb,
  ARRAY['Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- MCK Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'MCK Equipment', 'mck-equipment', 'MCK Equipment (Marquis Commercial Kitchen) is a Canadian commercial kitchen equipment retailer with a Saskatoon showroom and Canada-wide online sales. It offers financing and leasing for hospitality equipment through partners Econolease and NewCap, including Rent-Try-Buy and lease-to-own options.',
  'https://mckonline.ca', '1-833-978-8833', 'sales@mckequipment.ca',
  '{"street":"3603 Millar Ave #4","city":"Saskatoon","province":"Saskatchewan","postal_code":"S7P 0B2"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Canadian Restaurant Supply
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Canadian Restaurant Supply', 'canadian-restaurant-supply', 'Canadian Restaurant Supply is a Kelowna based commercial kitchen design and equipment firm with a team of consultants, designers and project managers. It outfits restaurants with comprehensive kitchen design, equipment supply and consulting, and offers financing and leasing through Econolease.',
  'https://www.canadianrestaurantsupply.com', '(250) 979-1442', NULL,
  '{"street":"6 - 2604 Enterprise Way","city":"Kelowna","province":"British Columbia","postal_code":"V1X 7Y5"}'::jsonb,
  ARRAY['Restaurant Consulting', 'Design & Technical Drawings', 'Equipment Consulting', 'Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6.5,"industry_experience":6.5,"response_time":6,"pricing_transparency":6,"certifications":6}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Commercial Kitchen Build
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Commercial Kitchen Build', 'commercial-kitchen-build', 'Commercial Kitchen Build (operated by Apex Consulting and Management) is a Mississauga based commercial kitchen design-build firm. It designs, supplies and installs commercial kitchen equipment, exhaust hood systems and fire suppression for GTA foodservice businesses, with a focus on fire-code and building-standard compliance.',
  'https://commercialkitchenbuild.ca', '(905) 616-2523', 'office@constructionatapex.com',
  '{"street":"60 Bristol Rd East, Suite 249","city":"Mississauga","province":"Ontario","postal_code":"L4Z 3K8"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Design & Technical Drawings', 'Installation Services', 'Equipment Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- KAF Bar Supplies
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'KAF Bar Supplies', 'kaf-bar-supplies', 'KAF Bar Supplies is a Mississauga based supplier serving bars and restaurants across the GTA. Alongside commercial kitchen and bar equipment, it offers custom kitchen and bar design, layout and space planning, equipment consulting and sourcing, and broader restaurant and bar planning services.',
  'https://kafsupplies.com', '(905) 997-5231', 'info@kafsupplies.com',
  '{"street":"4140A Sladeview Crescent","city":"Mississauga","province":"Ontario","postal_code":"L5L 6A1"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Design & Technical Drawings', 'Equipment Consulting', 'Restaurant Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Old Fashioned Restaurants
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Old Fashioned Restaurants', 'ofr-concepts', 'Old Fashioned Restaurants (OFR Concepts) is a Toronto hospitality consulting firm founded in 2014. It helps restaurateurs open and operate profitable businesses through concept design, pre-construction project management, kitchen and equipment layout, equipment sourcing, menu engineering and operational audits.',
  'https://www.ofrconcepts.ca', '(416) 677-1281', NULL,
  '{"street":"19 Barberry Place","city":"Toronto","province":"Ontario","postal_code":"M2K 3E3"}'::jsonb,
  ARRAY['Restaurant Consulting', 'Design & Technical Drawings', 'Equipment Consulting', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Enterprise Restaurant Consulting
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Enterprise Restaurant Consulting', 'enterprise-restaurant-consulting', 'Enterprise Restaurant Consulting is a Mississauga based restaurant and franchise consulting firm helping quick-service and full-service brands scale. It delivers operations and SOP development, menu engineering and food costing, franchise development, and kitchen design with equipment layout and sourcing.',
  'https://erestaurantconsulting.ca', '(647) 209-4153', 'support@erc1.net',
  '{"street":"5800 Ambler Dr., Unit 114","city":"Mississauga","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting', 'Design & Technical Drawings', 'Equipment Consulting', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Fincap Financial Group
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Fincap Financial Group', 'fincap-financial-group', 'Fincap Financial Group is a Canadian equipment finance company that arranges restaurant equipment financing and leasing for new and used equipment such as pizza ovens, fryers, dishwashers, ice machines and cold rooms, working with a network of lenders for fast approvals.',
  'https://www.fincapfinancialgroup.ca', '(819) 643-9997', 'info@fincapfinancialgroup.ca',
  '{"street":"510 Blvd. Maloney E, Suite 104","city":"Gatineau","province":"Quebec","postal_code":"J8P 1E7"}'::jsonb,
  ARRAY['Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Zanduco Restaurant Equipment & Supplies
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Zanduco Restaurant Equipment & Supplies', 'zanduco', 'Zanduco is a Mississauga based online commercial kitchen equipment and supplies retailer serving Canada and the US. It carries a full catalog of commercial kitchen equipment and smallwares and offers a documented Price Match Guarantee on qualifying products.',
  'https://www.zanduco.com/ca', '1-855-926-3826', 'sales@zanduco.com',
  '{"street":"2185 N Sheridan Way","city":"Mississauga","province":"Ontario","postal_code":"L5K 1A4"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Price Match']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- The Cook’s Mate
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'The Cook’s Mate', 'the-cooks-mate', 'The Cook’s Mate is a Scarborough based commercial restaurant equipment supplier offering equipment sales, delivery and installation across Ontario, plus leasing and financing through a partner. It operates a RATIONAL demo kitchen and supports operators before and after purchase.',
  'https://thecooksmate.com', '(416) 759-8122', NULL,
  '{"street":"505 Ellesmere Road, Unit 1","city":"Toronto","province":"Ontario","postal_code":"M1R 4E5"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Consulting', 'Equipment Financing', 'Equipment Leasing', 'Installation Services']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6.5,"customer_reviews":6,"industry_experience":6.5,"response_time":6,"pricing_transparency":5.5,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- iFoodEquipment.ca
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'iFoodEquipment.ca', 'ifoodequipment', 'iFoodEquipment.ca is a family-owned Hamilton based restaurant equipment and supplies dealer selling refrigeration, food prep tools and smallwares Canada-wide. It runs a restaurant equipment rental and financing program with a 12-month rent-try-buy that can convert to lease-to-own.',
  'https://ifoodequipment.ca', '(905) 544-0577', NULL,
  '{"street":"223 Avondale Street","city":"Hamilton","province":"Ontario","postal_code":"L8L 7C4"}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Equipment Financing', 'Equipment Leasing']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Ontario Restaurant Supply
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Ontario Restaurant Supply', 'ontario-restaurant-supply', 'Ontario Restaurant Supply is a locally owned, family operated London, Ontario restaurant equipment store carrying brand-name new and used commercial kitchen equipment. It advertises a price match guarantee and lowest-price positioning on brand-name equipment.',
  'https://ontariorestaurantsupply.ca', '(226) 330-0333', NULL,
  '{"street":"530 First Street","city":"London","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Commercial Equipment Procurement', 'Price Match']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- A1 Cash and Carry
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'A1 Cash and Carry', 'a1-cash-and-carry', 'A1 Cash and Carry is a wholesale food and restaurant supply cash-and-carry chain headquartered in Mississauga, with additional GTA stores in Etobicoke, North York and Burlington. It sells restaurant equipment, wares and supplies online and in-store.',
  'https://www.a1cashandcarry.com', '(905) 676-9950', 'ecommerce@a1cashandcarry.com',
  '{"street":"6400 Kennedy Road","city":"Mississauga","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Franchise 360
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Franchise 360', 'franchise-360', 'Franchise 360 is a Toronto restaurant and franchise consultancy guiding projects from inception to launch. It provides business planning and feasibility assessment, branding, menu development, standard operating procedures, build-out management, recruiting and ongoing operational and management services.',
  'https://franchise360.ca', '(647) 945-7999', 'info@franchise360.ca',
  '{"street":null,"city":"Toronto","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- MP HVAC Corporation
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'MP HVAC Corporation', 'mp-hvac', 'MP HVAC Corporation is a Scarborough based HVAC company serving Toronto and the GTA, specializing in commercial kitchen exhaust hood and canopy installation, make-up air units, ductwork, exhaust fans and UL 300 fire suppression, including complete turnkey installs.',
  'https://www.mphvaccorporation.com', '(416) 825-0911', 'info@mphvaccorporation.com',
  '{"street":null,"city":"Scarborough","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Installation Services']::text[],
  ARRAY['TSSA Certified', 'UL 300 Fire Suppression', 'G1 Licensed Gas Technicians']::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Apex Electric and Mechanical
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Apex Electric and Mechanical', 'apex-electric-mechanical', 'Apex Electric and Mechanical is a Toronto and GTA contractor, established in 2016, that installs, repairs and inspects commercial kitchen hoods and exhaust systems for restaurants, ghost kitchens, food trucks, cafeterias and institutional foodservice, including Type I and II hoods, make-up air integration and Ansul fire suppression.',
  'https://apexelectricmechanical.ca', '(416) 273-9800', NULL,
  '{"street":"263 Dixon Road, Unit 1110","city":"Toronto","province":"Ontario","postal_code":"M9R 1R6"}'::jsonb,
  ARRAY['Installation Services']::text[],
  ARRAY['TSSA Certified Gas Contractor', 'ECRA/ESA Licensed Electrical Contractor', '313A Certified Refrigeration Mechanics', 'WSIB Registered']::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":6,"pricing_transparency":6,"certifications":5.5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Avondale Commercial Solutions
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Avondale Commercial Solutions', 'avondale-commercial-solutions', 'Avondale Commercial Solutions is a Hamilton, Ontario commercial kitchen consultant with over 20 years in the foodservice industry. It focuses on a straightforward approach to kitchen design, floor plan layouts, and equipment specification and procurement.',
  'https://avondale-commercial-solutions.ueniweb.com', NULL, NULL,
  '{"street":null,"city":"Hamilton","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Design & Technical Drawings', 'Equipment Consulting', 'Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":5.5,"pricing_transparency":5.5,"certifications":5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Toronto Restaurant Consultants
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Toronto Restaurant Consultants', 'toronto-restaurant-consultants', 'Toronto Restaurant Consultants is a Toronto restaurant consulting firm offering operations support, menu engineering, commercial kitchen design, culinary recruitment, and beverage, POS and marketing services for quick-service through fine-dining establishments.',
  'https://www.restaurantconsultant.ca', NULL, NULL,
  '{"street":null,"city":"Toronto","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting', 'Design & Technical Drawings']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":5.5,"pricing_transparency":5.5,"certifications":5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Fried Sage Hospitality
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Fried Sage Hospitality', 'fried-sage-hospitality', 'Fried Sage Hospitality is a Hamilton, Ontario chef-led hospitality consultancy that partners with restaurants, hotels and food businesses on concept development, menu engineering, brand strategy and kitchen performance optimization.',
  'https://www.friedsage.com', NULL, NULL,
  '{"street":null,"city":"Hamilton","province":"Ontario","postal_code":null}'::jsonb,
  ARRAY['Restaurant Consulting']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":6,"customer_reviews":5.5,"industry_experience":6,"response_time":5.5,"pricing_transparency":5.5,"certifications":5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- MB Food Equipment
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'MB Food Equipment', 'mb-food-equipment', 'MB Food Equipment is an Oakville based dealer of used commercial foodservice equipment serving the GTA, carrying a large inventory and representing manufacturers from across the foodservice equipment industry.',
  'https://mbfoodequipment.com', '(289) 993-5999', 'mbfoodequipment@gmail.com',
  '{"street":"447 Speers Road, Unit 15","city":"Oakville","province":"Ontario","postal_code":"L6K 3S7"}'::jsonb,
  ARRAY['Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":5.5,"customer_reviews":5.5,"industry_experience":5.5,"response_time":5.5,"pricing_transparency":5,"certifications":5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Kitchen Treasure Restaurant Supplies
insert into public.companies (name, slug, description, website_url, phone, email, address, services, certifications, partners, is_featured, ranking_breakdown)
values (
  'Kitchen Treasure Restaurant Supplies', 'kitchen-treasure', 'Kitchen Treasure Restaurant Supplies is a Scarborough based restaurant and kitchen supply retailer and wholesaler established in 2012, with two Scarborough locations open to the public for both retail and wholesale customers.',
  'https://www.kitchentreasuresupplies.com', '(416) 832-1361', NULL,
  '{"street":"955 Middlefield Rd, Unit 4","city":"Scarborough","province":"Ontario","postal_code":"M1V 5E2"}'::jsonb,
  ARRAY['Commercial Equipment Procurement']::text[],
  '{}'::text[],
  '[]'::jsonb, false, '{"service_range":5.5,"customer_reviews":5.5,"industry_experience":5.5,"response_time":5.5,"pricing_transparency":5,"certifications":5}'::jsonb
)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, website_url = excluded.website_url,
  phone = excluded.phone, email = excluded.email, address = excluded.address,
  services = excluded.services, certifications = excluded.certifications,
  ranking_breakdown = excluded.ranking_breakdown;

-- Two factual FAQs per company, built from verified data.
update public.companies set faq = jsonb_build_array(
  jsonb_build_object('question', 'Where is ' || name || ' located?',
    'answer', name || ' is based in ' || coalesce((address->>'street') || ', ', '') || (address->>'city') || ', ' || (address->>'province') || ', Canada.'),
  jsonb_build_object('question', 'What services does ' || name || ' offer for commercial kitchens?',
    'answer', name || ' offers ' || array_to_string(services, ', ') || '.')
) where slug in ('tfi-food-equipment', 'united-trimen', 'doyon-despres', 'hesco-foodservice', 'hubert-canada', 'econolease', 'bouthillette-parizeau', 'browne-foodservice', 'celco', 'bakemax', 'kaizen-foodservice', 'paragon-food-equipment', 'gbs-foodservice', 'fsstrategy', 'newcap-leasing', 'babak-food-equipment', 'adl-fournisseur-commercial', 'jfs-restaurant-equipment', 'krg-hospitality', 'brama', 'foundry-kitchens', 'proxpedite', 'continental-restaurant-equipment', 'mehmi-financial-group', 'mck-equipment', 'canadian-restaurant-supply', 'commercial-kitchen-build', 'kaf-bar-supplies', 'ofr-concepts', 'enterprise-restaurant-consulting', 'fincap-financial-group', 'zanduco', 'the-cooks-mate', 'ifoodequipment', 'ontario-restaurant-supply', 'a1-cash-and-carry', 'franchise-360', 'mp-hvac', 'apex-electric-mechanical', 'avondale-commercial-solutions', 'toronto-restaurant-consultants', 'fried-sage-hospitality', 'mb-food-equipment', 'kitchen-treasure');

-- Self-hosted brand logos (files live under public/logos/).
update public.companies set logo_url = '/logos/tfi-food-equipment.png' where slug = 'tfi-food-equipment';
update public.companies set logo_url = '/logos/united-trimen.png' where slug = 'united-trimen';
update public.companies set logo_url = '/logos/doyon-despres.png' where slug = 'doyon-despres';
update public.companies set logo_url = '/logos/hesco-foodservice.png' where slug = 'hesco-foodservice';
update public.companies set logo_url = '/logos/hubert-canada.png' where slug = 'hubert-canada';
update public.companies set logo_url = '/logos/econolease.png' where slug = 'econolease';
update public.companies set logo_url = '/logos/bouthillette-parizeau.png' where slug = 'bouthillette-parizeau';
update public.companies set logo_url = '/logos/browne-foodservice.png' where slug = 'browne-foodservice';
update public.companies set logo_url = '/logos/celco.png' where slug = 'celco';
update public.companies set logo_url = '/logos/bakemax.png' where slug = 'bakemax';
update public.companies set logo_url = '/logos/kaizen-foodservice.png' where slug = 'kaizen-foodservice';
update public.companies set logo_url = '/logos/paragon-food-equipment.png' where slug = 'paragon-food-equipment';
update public.companies set logo_url = '/logos/gbs-foodservice.png' where slug = 'gbs-foodservice';
update public.companies set logo_url = '/logos/fsstrategy.png' where slug = 'fsstrategy';
update public.companies set logo_url = '/logos/newcap-leasing.svg' where slug = 'newcap-leasing';
update public.companies set logo_url = '/logos/babak-food-equipment.png' where slug = 'babak-food-equipment';
update public.companies set logo_url = '/logos/adl-fournisseur-commercial.png' where slug = 'adl-fournisseur-commercial';
update public.companies set logo_url = '/logos/jfs-restaurant-equipment.png' where slug = 'jfs-restaurant-equipment';
update public.companies set logo_url = '/logos/krg-hospitality.png' where slug = 'krg-hospitality';
update public.companies set logo_url = '/logos/brama.png' where slug = 'brama';
update public.companies set logo_url = '/logos/foundry-kitchens.png' where slug = 'foundry-kitchens';
update public.companies set logo_url = '/logos/proxpedite.png' where slug = 'proxpedite';
update public.companies set logo_url = '/logos/continental-restaurant-equipment.png' where slug = 'continental-restaurant-equipment';
update public.companies set logo_url = '/logos/mehmi-financial-group.png' where slug = 'mehmi-financial-group';
update public.companies set logo_url = '/logos/mck-equipment.png' where slug = 'mck-equipment';
update public.companies set logo_url = '/logos/canadian-restaurant-supply.png' where slug = 'canadian-restaurant-supply';
update public.companies set logo_url = '/logos/commercial-kitchen-build.png' where slug = 'commercial-kitchen-build';
update public.companies set logo_url = '/logos/kaf-bar-supplies.png' where slug = 'kaf-bar-supplies';
update public.companies set logo_url = '/logos/enterprise-restaurant-consulting.png' where slug = 'enterprise-restaurant-consulting';
update public.companies set logo_url = '/logos/fincap-financial-group.png' where slug = 'fincap-financial-group';
update public.companies set logo_url = '/logos/zanduco.png' where slug = 'zanduco';
update public.companies set logo_url = '/logos/the-cooks-mate.png' where slug = 'the-cooks-mate';
update public.companies set logo_url = '/logos/ifoodequipment.png' where slug = 'ifoodequipment';
update public.companies set logo_url = '/logos/ontario-restaurant-supply.png' where slug = 'ontario-restaurant-supply';
update public.companies set logo_url = '/logos/a1-cash-and-carry.png' where slug = 'a1-cash-and-carry';
update public.companies set logo_url = '/logos/franchise-360.png' where slug = 'franchise-360';
update public.companies set logo_url = '/logos/mp-hvac.png' where slug = 'mp-hvac';
update public.companies set logo_url = '/logos/apex-electric-mechanical.png' where slug = 'apex-electric-mechanical';
update public.companies set logo_url = '/logos/avondale-commercial-solutions.png' where slug = 'avondale-commercial-solutions';
update public.companies set logo_url = '/logos/fried-sage-hospitality.png' where slug = 'fried-sage-hospitality';
update public.companies set logo_url = '/logos/mb-food-equipment.png' where slug = 'mb-food-equipment';
update public.companies set logo_url = '/logos/kitchen-treasure.png' where slug = 'kitchen-treasure';

alter table public.companies enable trigger trg_company_changed;

commit;
